//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eMediShop.HealthCard {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://exprohelp.com/", ConfigurationName="HealthCard.HealthCard_WebServicesSoap")]
    public interface HealthCard_WebServicesSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://exprohelp.com/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://exprohelp.com/GetDistrictList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetDistrictList(string Country, string State_Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://exprohelp.com/GetStateList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetStateList(string Country);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://exprohelp.com/GetOnLineOrderInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetOnLineOrderInfo(string unit_id, string order_no, string what);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://exprohelp.com/HealthCardRegister", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet HealthCardRegister(out string processInfo, string unit_id, string from, string to, string logic, string login_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://exprohelp.com/GetCard_Queries", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetCard_Queries(out string processInfo, string LabCode, string card_no, string mobile, string prm_1, string prm_2, string Logic);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://exprohelp.com/Card_Info_insert", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Card_Info_insert(eMediShop.HealthCard.CustomerCard obj, string dbname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://exprohelp.com/Insert_CustCardInfowithMember", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Insert_CustCardInfowithMember(
                    string labcode, 
                    string card_no, 
                    string member_id, 
                    string m_type, 
                    string cust_name, 
                    string gender, 
                    string dob, 
                    string mobileno, 
                    string area, 
                    string Locality, 
                    string district, 
                    string state, 
                    string email, 
                    string pin, 
                    string logic, 
                    System.Data.DataSet dsmembers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://exprohelp.com/Insert_CustCardInfowithMemberNew", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Insert_CustCardInfowithMemberNew(
                    string labcode, 
                    string card_no, 
                    string member_id, 
                    string m_type, 
                    string cust_name, 
                    string gender, 
                    string dob, 
                    string mobileno, 
                    string area, 
                    string Locality, 
                    string district, 
                    string state, 
                    string email, 
                    string pin, 
                    string logic, 
                    System.Data.DataSet dsmembers, 
                    string login_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://exprohelp.com/Insert_UpdateCustCardMemebers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Insert_UpdateCustCardMemebers(
                    string labcode, 
                    string card_no, 
                    string member_id, 
                    string m_type, 
                    string cust_name, 
                    string gender, 
                    string dob, 
                    string mobileno, 
                    string area, 
                    string Locality, 
                    string district, 
                    string state, 
                    string email, 
                    string pin, 
                    string logic, 
                    System.Data.DataSet dsmembers, 
                    string login_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://exprohelp.com/Ins_UnProcessCArd", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Ins_UnProcessCArd(
                    string logic, 
                    string loginid, 
                    string card_type, 
                    string Cust_Name, 
                    string dob, 
                    string Area, 
                    string Locality, 
                    string District, 
                    string State, 
                    string Country, 
                    string PIN, 
                    string PhoneNo, 
                    string MobileNo, 
                    string email, 
                    string Spouse_Name, 
                    string Spouse_dob, 
                    string Child_Name_1, 
                    string Child_DOB_1, 
                    string Child_Name_2, 
                    string Child_DOB_2, 
                    string Child_Name_3, 
                    string Child_DOB_3, 
                    string Child_Name_4, 
                    string Child_DOB_4, 
                    string Child_Name_5, 
                    string Child_DOB_5, 
                    string Card_No, 
                    string inst_code, 
                    string dist_type, 
                    decimal purch_amount, 
                    decimal FHQF_amt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://exprohelp.com/ReplaceCard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ReplaceCard(string old_card_no, string new_card_no, string unit_id, string logic, string login_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://exprohelp.com/GetACardInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetACardInfo(string Card_No);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://exprohelp.com/ShiftSchedule_Bulk", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ShiftSchedule_Bulk(string old_login, string new_login, string sch_date, string bulk_by);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://exprohelp.com/GetACardStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetACardStatus(string Card_No, string unit_id, string logic);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://exprohelp.com/HealthCardActivationRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HealthCardActivationRequest(string Card_No);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://exprohelp.com/ActivateHealthCard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ActivateHealthCard(string unit_id, string login_id, string Card_No);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://exprohelp.com/ActivateCard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ActivateCard(string ActivationNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://exprohelp.com/HealthCard_GetInfoForPoS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet HealthCard_GetInfoForPoS(out string processInfo, string unit_id, string SearchString, string logic);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://exprohelp.com/Promotional_Queries", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Promotional_Queries(out string processInfo, string card_no, string prm_1, string prm_2, int prm_3, string logic);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://exprohelp.com/ValidateCoupon", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ValidateCoupon(string unit_id, string i_code, string coupon_no, string patient_id, string prm_1, string logic);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://exprohelp.com/HealthCardQueries", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet HealthCardQueries(out string processInfo, string unit_id, string logic, string from, string to, string prm_1, string prm_2, string login_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://exprohelp.com/RCMCall_Report", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet RCMCall_Report(out string processInfo, string Logic, string from, string to, string prm_1, string prm_2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://exprohelp.com/Insert_CustCall_Log", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Insert_CustCall_Log(out string processInfo, int Auto_id, string card_no, string call_type, string login_id, string Remarks, string Logic);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://exprohelp.com/InsertRegularOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsertRegularOrder(out string processInfo, string card_no, string item_id, string new_med, string rec_flag, string login_id, string Logic);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://exprohelp.com/RCM_SmallQuerys", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet RCM_SmallQuerys(out string processInfo, string card_no, string date, string time, string unit_id, string Logic);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://exprohelp.com/RCMSmallQueries", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet RCMSmallQueries(out string processInfo, string card_no, string date, string time, string unit_id, string Logic);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://exprohelp.com/CallingCard_queries", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet CallingCard_queries(out string processInfo, string unit_id, string login_id, string logic, string prm_1, string prm_2, string prm_3);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://exprohelp.com/SearchProduct", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SearchProduct(out string processInfo, string search);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://exprohelp.com/RCM_ProductInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet RCM_ProductInfo(out string processInfo, string logic, string card_no, string order_no, string login_id, string unit_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://exprohelp.com/RegisterPatient", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string RegisterPatient(string unit_Manager_Contact, string card_no, string pt_name, string gender, string address, string mobile_no, string p_phone_no, string date_smp_collection, string time_sample_collection, string Investd, string GenFrom, string login_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://exprohelp.com/RCCreateData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string RCCreateData(string card_no, string rmd_date, string rmd_time, string unit_id, string remark, string lastcallinfo, string login_id, string Logic);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://exprohelp.com/RCM_OnCallOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string RCM_OnCallOrder(string card_no, string cust_name, string shop_code, string order_no, string prod_code, string delivery_date, string delivery_time, int qty, string orderno, string newmedname, string login_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://exprohelp.com/RCM_CompleteOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string RCM_CompleteOrder(out string processInfo, string sh_code, string order_no, string card_no, string del_date, string del_time, string remark, string ref_by, string old_order_no, string sale_inv_no, string promo_flag, string prm_1, string logic);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://exprohelp.com/OrderTrackingReport", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet OrderTrackingReport(out string processInfo, string unit_id, string from, string to, string logic, string prm_1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://exprohelp.com/AuthenticateLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AuthenticateLogin(string unit_id, string login_id, string password, string accessFrom, string systemId, string database);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://exprohelp.com/QueryExecute", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void QueryExecute(string qry, string dbname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://exprohelp.com/GetQueryResult", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetQueryResult(string qry, string dbname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://exprohelp.com/HealthCardQueries_2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet HealthCardQueries_2(out string processInfo, string card_no, string logic, string prm_1, string prm_2, string login_id);
        
        // CODEGEN: Parameter 'data' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://exprohelp.com/OnlineOrder_Insert", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        eMediShop.HealthCard.OnlineOrder_InsertResponse OnlineOrder_Insert(eMediShop.HealthCard.OnlineOrder_InsertRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://exprohelp.com/Insert_OrderRemark", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Insert_OrderRemark(out string processInfo, string RemarkFrom, string order_no, string remark, string login_id);
        
        // CODEGEN: Parameter 'DownLoadFileResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://exprohelp.com/DownLoadFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        eMediShop.HealthCard.DownLoadFileResponse DownLoadFile(eMediShop.HealthCard.DownLoadFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://exprohelp.com/TPA_CardInsert", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string TPA_CardInsert(string Card_No, string loginid, string card_type, string Cust_Name, string Area, string Locality, string District, string State, string Country, string MobileNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://exprohelp.com/TPOrder_Insert", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string TPOrder_Insert(out string processInfo, string client_id, string card_no, string unit_id, string master_order, string login_id, string med_name, int qty, System.DateTime deldate, string order_no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://exprohelp.com/InformToPatient", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InformToPatient(string unit_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://exprohelp.com/Gen_SystemCouponNo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Gen_SystemCouponNo(out string processInfo, string card_no, string cust_name, string prm_1, string prm_2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://exprohelp.com/Insert_Modify_custOrderInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Insert_Modify_custOrderInfo(string order_no, string item_id, string old_item_id, string new_med, int qty, string cancel_flag, string Logic, string login_id);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://exprohelp.com/")]
    public partial class CustomerCard : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string payTypeField;
        
        private string distTypeField;
        
        private string logicField;
        
        private string login_idField;
        
        private string cardTypeField;
        
        private string cust_NameField;
        
        private System.DateTime dOBField;
        
        private string areaField;
        
        private string localityField;
        
        private string districtField;
        
        private string stateField;
        
        private string countryField;
        
        private string pINField;
        
        private string phoneNoField;
        
        private string mobileNoField;
        
        private string emailField;
        
        private string spouse_NameField;
        
        private System.DateTime spouse_DOBField;
        
        private string child_Name_1Field;
        
        private System.DateTime child_DOB_1Field;
        
        private string child_Name_2Field;
        
        private System.DateTime child_DOB_2Field;
        
        private string child_Name_3Field;
        
        private System.DateTime child_DOB_3Field;
        
        private string child_Name_4Field;
        
        private System.DateTime child_DOB_4Field;
        
        private string child_Name_5Field;
        
        private System.DateTime child_DOB_5Field;
        
        private string card_NoField;
        
        private string inst_CodeField;
        
        private System.DateTime actDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PayType {
            get {
                return this.payTypeField;
            }
            set {
                this.payTypeField = value;
                this.RaisePropertyChanged("PayType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DistType {
            get {
                return this.distTypeField;
            }
            set {
                this.distTypeField = value;
                this.RaisePropertyChanged("DistType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string logic {
            get {
                return this.logicField;
            }
            set {
                this.logicField = value;
                this.RaisePropertyChanged("logic");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string login_id {
            get {
                return this.login_idField;
            }
            set {
                this.login_idField = value;
                this.RaisePropertyChanged("login_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CardType {
            get {
                return this.cardTypeField;
            }
            set {
                this.cardTypeField = value;
                this.RaisePropertyChanged("CardType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Cust_Name {
            get {
                return this.cust_NameField;
            }
            set {
                this.cust_NameField = value;
                this.RaisePropertyChanged("Cust_Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime DOB {
            get {
                return this.dOBField;
            }
            set {
                this.dOBField = value;
                this.RaisePropertyChanged("DOB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Area {
            get {
                return this.areaField;
            }
            set {
                this.areaField = value;
                this.RaisePropertyChanged("Area");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Locality {
            get {
                return this.localityField;
            }
            set {
                this.localityField = value;
                this.RaisePropertyChanged("Locality");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string District {
            get {
                return this.districtField;
            }
            set {
                this.districtField = value;
                this.RaisePropertyChanged("District");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("Country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string PIN {
            get {
                return this.pINField;
            }
            set {
                this.pINField = value;
                this.RaisePropertyChanged("PIN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string PhoneNo {
            get {
                return this.phoneNoField;
            }
            set {
                this.phoneNoField = value;
                this.RaisePropertyChanged("PhoneNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string MobileNo {
            get {
                return this.mobileNoField;
            }
            set {
                this.mobileNoField = value;
                this.RaisePropertyChanged("MobileNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Spouse_Name {
            get {
                return this.spouse_NameField;
            }
            set {
                this.spouse_NameField = value;
                this.RaisePropertyChanged("Spouse_Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public System.DateTime Spouse_DOB {
            get {
                return this.spouse_DOBField;
            }
            set {
                this.spouse_DOBField = value;
                this.RaisePropertyChanged("Spouse_DOB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Child_Name_1 {
            get {
                return this.child_Name_1Field;
            }
            set {
                this.child_Name_1Field = value;
                this.RaisePropertyChanged("Child_Name_1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public System.DateTime Child_DOB_1 {
            get {
                return this.child_DOB_1Field;
            }
            set {
                this.child_DOB_1Field = value;
                this.RaisePropertyChanged("Child_DOB_1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string Child_Name_2 {
            get {
                return this.child_Name_2Field;
            }
            set {
                this.child_Name_2Field = value;
                this.RaisePropertyChanged("Child_Name_2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public System.DateTime Child_DOB_2 {
            get {
                return this.child_DOB_2Field;
            }
            set {
                this.child_DOB_2Field = value;
                this.RaisePropertyChanged("Child_DOB_2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string Child_Name_3 {
            get {
                return this.child_Name_3Field;
            }
            set {
                this.child_Name_3Field = value;
                this.RaisePropertyChanged("Child_Name_3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public System.DateTime Child_DOB_3 {
            get {
                return this.child_DOB_3Field;
            }
            set {
                this.child_DOB_3Field = value;
                this.RaisePropertyChanged("Child_DOB_3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string Child_Name_4 {
            get {
                return this.child_Name_4Field;
            }
            set {
                this.child_Name_4Field = value;
                this.RaisePropertyChanged("Child_Name_4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public System.DateTime Child_DOB_4 {
            get {
                return this.child_DOB_4Field;
            }
            set {
                this.child_DOB_4Field = value;
                this.RaisePropertyChanged("Child_DOB_4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string Child_Name_5 {
            get {
                return this.child_Name_5Field;
            }
            set {
                this.child_Name_5Field = value;
                this.RaisePropertyChanged("Child_Name_5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public System.DateTime Child_DOB_5 {
            get {
                return this.child_DOB_5Field;
            }
            set {
                this.child_DOB_5Field = value;
                this.RaisePropertyChanged("Child_DOB_5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string Card_No {
            get {
                return this.card_NoField;
            }
            set {
                this.card_NoField = value;
                this.RaisePropertyChanged("Card_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string Inst_Code {
            get {
                return this.inst_CodeField;
            }
            set {
                this.inst_CodeField = value;
                this.RaisePropertyChanged("Inst_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public System.DateTime ActDate {
            get {
                return this.actDateField;
            }
            set {
                this.actDateField = value;
                this.RaisePropertyChanged("ActDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineOrder_Insert", WrapperNamespace="http://exprohelp.com/", IsWrapped=true)]
    public partial class OnlineOrder_InsertRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://exprohelp.com/", Order=0)]
        public string card_no;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://exprohelp.com/", Order=1)]
        public string unit_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://exprohelp.com/", Order=2)]
        public string item_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://exprohelp.com/", Order=3)]
        public string new_med;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://exprohelp.com/", Order=4)]
        public int qty;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://exprohelp.com/", Order=5)]
        public string del_date;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://exprohelp.com/", Order=6)]
        public string del_time;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://exprohelp.com/", Order=7)]
        public string ref_by;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://exprohelp.com/", Order=8)]
        public string remark;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://exprohelp.com/", Order=9)]
        public string file_path;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://exprohelp.com/", Order=10)]
        public string order_no;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://exprohelp.com/", Order=11)]
        public string logic;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://exprohelp.com/", Order=12)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] data;
        
        public OnlineOrder_InsertRequest() {
        }
        
        public OnlineOrder_InsertRequest(string card_no, string unit_id, string item_id, string new_med, int qty, string del_date, string del_time, string ref_by, string remark, string file_path, string order_no, string logic, byte[] data) {
            this.card_no = card_no;
            this.unit_id = unit_id;
            this.item_id = item_id;
            this.new_med = new_med;
            this.qty = qty;
            this.del_date = del_date;
            this.del_time = del_time;
            this.ref_by = ref_by;
            this.remark = remark;
            this.file_path = file_path;
            this.order_no = order_no;
            this.logic = logic;
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineOrder_InsertResponse", WrapperNamespace="http://exprohelp.com/", IsWrapped=true)]
    public partial class OnlineOrder_InsertResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://exprohelp.com/", Order=0)]
        public string OnlineOrder_InsertResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://exprohelp.com/", Order=1)]
        public string processInfo;
        
        public OnlineOrder_InsertResponse() {
        }
        
        public OnlineOrder_InsertResponse(string OnlineOrder_InsertResult, string processInfo) {
            this.OnlineOrder_InsertResult = OnlineOrder_InsertResult;
            this.processInfo = processInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownLoadFile", WrapperNamespace="http://exprohelp.com/", IsWrapped=true)]
    public partial class DownLoadFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://exprohelp.com/", Order=0)]
        public string file_path;
        
        public DownLoadFileRequest() {
        }
        
        public DownLoadFileRequest(string file_path) {
            this.file_path = file_path;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownLoadFileResponse", WrapperNamespace="http://exprohelp.com/", IsWrapped=true)]
    public partial class DownLoadFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://exprohelp.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] DownLoadFileResult;
        
        public DownLoadFileResponse() {
        }
        
        public DownLoadFileResponse(byte[] DownLoadFileResult) {
            this.DownLoadFileResult = DownLoadFileResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HealthCard_WebServicesSoapChannel : eMediShop.HealthCard.HealthCard_WebServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HealthCard_WebServicesSoapClient : System.ServiceModel.ClientBase<eMediShop.HealthCard.HealthCard_WebServicesSoap>, eMediShop.HealthCard.HealthCard_WebServicesSoap {
        
        public HealthCard_WebServicesSoapClient() {
        }
        
        public HealthCard_WebServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HealthCard_WebServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HealthCard_WebServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HealthCard_WebServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Data.DataSet GetDistrictList(string Country, string State_Code) {
            return base.Channel.GetDistrictList(Country, State_Code);
        }
        
        public System.Data.DataSet GetStateList(string Country) {
            return base.Channel.GetStateList(Country);
        }
        
        public System.Data.DataSet GetOnLineOrderInfo(string unit_id, string order_no, string what) {
            return base.Channel.GetOnLineOrderInfo(unit_id, order_no, what);
        }
        
        public System.Data.DataSet HealthCardRegister(out string processInfo, string unit_id, string from, string to, string logic, string login_id) {
            return base.Channel.HealthCardRegister(out processInfo, unit_id, from, to, logic, login_id);
        }
        
        public System.Data.DataSet GetCard_Queries(out string processInfo, string LabCode, string card_no, string mobile, string prm_1, string prm_2, string Logic) {
            return base.Channel.GetCard_Queries(out processInfo, LabCode, card_no, mobile, prm_1, prm_2, Logic);
        }
        
        public string Card_Info_insert(eMediShop.HealthCard.CustomerCard obj, string dbname) {
            return base.Channel.Card_Info_insert(obj, dbname);
        }
        
        public string Insert_CustCardInfowithMember(
                    string labcode, 
                    string card_no, 
                    string member_id, 
                    string m_type, 
                    string cust_name, 
                    string gender, 
                    string dob, 
                    string mobileno, 
                    string area, 
                    string Locality, 
                    string district, 
                    string state, 
                    string email, 
                    string pin, 
                    string logic, 
                    System.Data.DataSet dsmembers) {
            return base.Channel.Insert_CustCardInfowithMember(labcode, card_no, member_id, m_type, cust_name, gender, dob, mobileno, area, Locality, district, state, email, pin, logic, dsmembers);
        }
        
        public string Insert_CustCardInfowithMemberNew(
                    string labcode, 
                    string card_no, 
                    string member_id, 
                    string m_type, 
                    string cust_name, 
                    string gender, 
                    string dob, 
                    string mobileno, 
                    string area, 
                    string Locality, 
                    string district, 
                    string state, 
                    string email, 
                    string pin, 
                    string logic, 
                    System.Data.DataSet dsmembers, 
                    string login_id) {
            return base.Channel.Insert_CustCardInfowithMemberNew(labcode, card_no, member_id, m_type, cust_name, gender, dob, mobileno, area, Locality, district, state, email, pin, logic, dsmembers, login_id);
        }
        
        public string Insert_UpdateCustCardMemebers(
                    string labcode, 
                    string card_no, 
                    string member_id, 
                    string m_type, 
                    string cust_name, 
                    string gender, 
                    string dob, 
                    string mobileno, 
                    string area, 
                    string Locality, 
                    string district, 
                    string state, 
                    string email, 
                    string pin, 
                    string logic, 
                    System.Data.DataSet dsmembers, 
                    string login_id) {
            return base.Channel.Insert_UpdateCustCardMemebers(labcode, card_no, member_id, m_type, cust_name, gender, dob, mobileno, area, Locality, district, state, email, pin, logic, dsmembers, login_id);
        }
        
        public string Ins_UnProcessCArd(
                    string logic, 
                    string loginid, 
                    string card_type, 
                    string Cust_Name, 
                    string dob, 
                    string Area, 
                    string Locality, 
                    string District, 
                    string State, 
                    string Country, 
                    string PIN, 
                    string PhoneNo, 
                    string MobileNo, 
                    string email, 
                    string Spouse_Name, 
                    string Spouse_dob, 
                    string Child_Name_1, 
                    string Child_DOB_1, 
                    string Child_Name_2, 
                    string Child_DOB_2, 
                    string Child_Name_3, 
                    string Child_DOB_3, 
                    string Child_Name_4, 
                    string Child_DOB_4, 
                    string Child_Name_5, 
                    string Child_DOB_5, 
                    string Card_No, 
                    string inst_code, 
                    string dist_type, 
                    decimal purch_amount, 
                    decimal FHQF_amt) {
            return base.Channel.Ins_UnProcessCArd(logic, loginid, card_type, Cust_Name, dob, Area, Locality, District, State, Country, PIN, PhoneNo, MobileNo, email, Spouse_Name, Spouse_dob, Child_Name_1, Child_DOB_1, Child_Name_2, Child_DOB_2, Child_Name_3, Child_DOB_3, Child_Name_4, Child_DOB_4, Child_Name_5, Child_DOB_5, Card_No, inst_code, dist_type, purch_amount, FHQF_amt);
        }
        
        public string ReplaceCard(string old_card_no, string new_card_no, string unit_id, string logic, string login_id) {
            return base.Channel.ReplaceCard(old_card_no, new_card_no, unit_id, logic, login_id);
        }
        
        public System.Data.DataSet GetACardInfo(string Card_No) {
            return base.Channel.GetACardInfo(Card_No);
        }
        
        public string ShiftSchedule_Bulk(string old_login, string new_login, string sch_date, string bulk_by) {
            return base.Channel.ShiftSchedule_Bulk(old_login, new_login, sch_date, bulk_by);
        }
        
        public string GetACardStatus(string Card_No, string unit_id, string logic) {
            return base.Channel.GetACardStatus(Card_No, unit_id, logic);
        }
        
        public string HealthCardActivationRequest(string Card_No) {
            return base.Channel.HealthCardActivationRequest(Card_No);
        }
        
        public string ActivateHealthCard(string unit_id, string login_id, string Card_No) {
            return base.Channel.ActivateHealthCard(unit_id, login_id, Card_No);
        }
        
        public System.Data.DataSet ActivateCard(string ActivationNo) {
            return base.Channel.ActivateCard(ActivationNo);
        }
        
        public System.Data.DataSet HealthCard_GetInfoForPoS(out string processInfo, string unit_id, string SearchString, string logic) {
            return base.Channel.HealthCard_GetInfoForPoS(out processInfo, unit_id, SearchString, logic);
        }
        
        public System.Data.DataSet Promotional_Queries(out string processInfo, string card_no, string prm_1, string prm_2, int prm_3, string logic) {
            return base.Channel.Promotional_Queries(out processInfo, card_no, prm_1, prm_2, prm_3, logic);
        }
        
        public string ValidateCoupon(string unit_id, string i_code, string coupon_no, string patient_id, string prm_1, string logic) {
            return base.Channel.ValidateCoupon(unit_id, i_code, coupon_no, patient_id, prm_1, logic);
        }
        
        public System.Data.DataSet HealthCardQueries(out string processInfo, string unit_id, string logic, string from, string to, string prm_1, string prm_2, string login_id) {
            return base.Channel.HealthCardQueries(out processInfo, unit_id, logic, from, to, prm_1, prm_2, login_id);
        }
        
        public System.Data.DataSet RCMCall_Report(out string processInfo, string Logic, string from, string to, string prm_1, string prm_2) {
            return base.Channel.RCMCall_Report(out processInfo, Logic, from, to, prm_1, prm_2);
        }
        
        public string Insert_CustCall_Log(out string processInfo, int Auto_id, string card_no, string call_type, string login_id, string Remarks, string Logic) {
            return base.Channel.Insert_CustCall_Log(out processInfo, Auto_id, card_no, call_type, login_id, Remarks, Logic);
        }
        
        public string InsertRegularOrder(out string processInfo, string card_no, string item_id, string new_med, string rec_flag, string login_id, string Logic) {
            return base.Channel.InsertRegularOrder(out processInfo, card_no, item_id, new_med, rec_flag, login_id, Logic);
        }
        
        public System.Data.DataSet RCM_SmallQuerys(out string processInfo, string card_no, string date, string time, string unit_id, string Logic) {
            return base.Channel.RCM_SmallQuerys(out processInfo, card_no, date, time, unit_id, Logic);
        }
        
        public System.Data.DataSet RCMSmallQueries(out string processInfo, string card_no, string date, string time, string unit_id, string Logic) {
            return base.Channel.RCMSmallQueries(out processInfo, card_no, date, time, unit_id, Logic);
        }
        
        public System.Data.DataSet CallingCard_queries(out string processInfo, string unit_id, string login_id, string logic, string prm_1, string prm_2, string prm_3) {
            return base.Channel.CallingCard_queries(out processInfo, unit_id, login_id, logic, prm_1, prm_2, prm_3);
        }
        
        public System.Data.DataSet SearchProduct(out string processInfo, string search) {
            return base.Channel.SearchProduct(out processInfo, search);
        }
        
        public System.Data.DataSet RCM_ProductInfo(out string processInfo, string logic, string card_no, string order_no, string login_id, string unit_id) {
            return base.Channel.RCM_ProductInfo(out processInfo, logic, card_no, order_no, login_id, unit_id);
        }
        
        public string RegisterPatient(string unit_Manager_Contact, string card_no, string pt_name, string gender, string address, string mobile_no, string p_phone_no, string date_smp_collection, string time_sample_collection, string Investd, string GenFrom, string login_id) {
            return base.Channel.RegisterPatient(unit_Manager_Contact, card_no, pt_name, gender, address, mobile_no, p_phone_no, date_smp_collection, time_sample_collection, Investd, GenFrom, login_id);
        }
        
        public string RCCreateData(string card_no, string rmd_date, string rmd_time, string unit_id, string remark, string lastcallinfo, string login_id, string Logic) {
            return base.Channel.RCCreateData(card_no, rmd_date, rmd_time, unit_id, remark, lastcallinfo, login_id, Logic);
        }
        
        public string RCM_OnCallOrder(string card_no, string cust_name, string shop_code, string order_no, string prod_code, string delivery_date, string delivery_time, int qty, string orderno, string newmedname, string login_id) {
            return base.Channel.RCM_OnCallOrder(card_no, cust_name, shop_code, order_no, prod_code, delivery_date, delivery_time, qty, orderno, newmedname, login_id);
        }
        
        public string RCM_CompleteOrder(out string processInfo, string sh_code, string order_no, string card_no, string del_date, string del_time, string remark, string ref_by, string old_order_no, string sale_inv_no, string promo_flag, string prm_1, string logic) {
            return base.Channel.RCM_CompleteOrder(out processInfo, sh_code, order_no, card_no, del_date, del_time, remark, ref_by, old_order_no, sale_inv_no, promo_flag, prm_1, logic);
        }
        
        public System.Data.DataSet OrderTrackingReport(out string processInfo, string unit_id, string from, string to, string logic, string prm_1) {
            return base.Channel.OrderTrackingReport(out processInfo, unit_id, from, to, logic, prm_1);
        }
        
        public string AuthenticateLogin(string unit_id, string login_id, string password, string accessFrom, string systemId, string database) {
            return base.Channel.AuthenticateLogin(unit_id, login_id, password, accessFrom, systemId, database);
        }
        
        public void QueryExecute(string qry, string dbname) {
            base.Channel.QueryExecute(qry, dbname);
        }
        
        public System.Data.DataSet GetQueryResult(string qry, string dbname) {
            return base.Channel.GetQueryResult(qry, dbname);
        }
        
        public System.Data.DataSet HealthCardQueries_2(out string processInfo, string card_no, string logic, string prm_1, string prm_2, string login_id) {
            return base.Channel.HealthCardQueries_2(out processInfo, card_no, logic, prm_1, prm_2, login_id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eMediShop.HealthCard.OnlineOrder_InsertResponse eMediShop.HealthCard.HealthCard_WebServicesSoap.OnlineOrder_Insert(eMediShop.HealthCard.OnlineOrder_InsertRequest request) {
            return base.Channel.OnlineOrder_Insert(request);
        }
        
        public string OnlineOrder_Insert(string card_no, string unit_id, string item_id, string new_med, int qty, string del_date, string del_time, string ref_by, string remark, string file_path, string order_no, string logic, byte[] data, out string processInfo) {
            eMediShop.HealthCard.OnlineOrder_InsertRequest inValue = new eMediShop.HealthCard.OnlineOrder_InsertRequest();
            inValue.card_no = card_no;
            inValue.unit_id = unit_id;
            inValue.item_id = item_id;
            inValue.new_med = new_med;
            inValue.qty = qty;
            inValue.del_date = del_date;
            inValue.del_time = del_time;
            inValue.ref_by = ref_by;
            inValue.remark = remark;
            inValue.file_path = file_path;
            inValue.order_no = order_no;
            inValue.logic = logic;
            inValue.data = data;
            eMediShop.HealthCard.OnlineOrder_InsertResponse retVal = ((eMediShop.HealthCard.HealthCard_WebServicesSoap)(this)).OnlineOrder_Insert(inValue);
            processInfo = retVal.processInfo;
            return retVal.OnlineOrder_InsertResult;
        }
        
        public string Insert_OrderRemark(out string processInfo, string RemarkFrom, string order_no, string remark, string login_id) {
            return base.Channel.Insert_OrderRemark(out processInfo, RemarkFrom, order_no, remark, login_id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eMediShop.HealthCard.DownLoadFileResponse eMediShop.HealthCard.HealthCard_WebServicesSoap.DownLoadFile(eMediShop.HealthCard.DownLoadFileRequest request) {
            return base.Channel.DownLoadFile(request);
        }
        
        public byte[] DownLoadFile(string file_path) {
            eMediShop.HealthCard.DownLoadFileRequest inValue = new eMediShop.HealthCard.DownLoadFileRequest();
            inValue.file_path = file_path;
            eMediShop.HealthCard.DownLoadFileResponse retVal = ((eMediShop.HealthCard.HealthCard_WebServicesSoap)(this)).DownLoadFile(inValue);
            return retVal.DownLoadFileResult;
        }
        
        public string TPA_CardInsert(string Card_No, string loginid, string card_type, string Cust_Name, string Area, string Locality, string District, string State, string Country, string MobileNo) {
            return base.Channel.TPA_CardInsert(Card_No, loginid, card_type, Cust_Name, Area, Locality, District, State, Country, MobileNo);
        }
        
        public string TPOrder_Insert(out string processInfo, string client_id, string card_no, string unit_id, string master_order, string login_id, string med_name, int qty, System.DateTime deldate, string order_no) {
            return base.Channel.TPOrder_Insert(out processInfo, client_id, card_no, unit_id, master_order, login_id, med_name, qty, deldate, order_no);
        }
        
        public string InformToPatient(string unit_id) {
            return base.Channel.InformToPatient(unit_id);
        }
        
        public string Gen_SystemCouponNo(out string processInfo, string card_no, string cust_name, string prm_1, string prm_2) {
            return base.Channel.Gen_SystemCouponNo(out processInfo, card_no, cust_name, prm_1, prm_2);
        }
        
        public string Insert_Modify_custOrderInfo(string order_no, string item_id, string old_item_id, string new_med, int qty, string cancel_flag, string Logic, string login_id) {
            return base.Channel.Insert_Modify_custOrderInfo(order_no, item_id, old_item_id, new_med, qty, cancel_flag, Logic, login_id);
        }
    }
}
