//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eMediShop.his_proxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http:www.itdoseinfo.com/2012/11/17", ConfigurationName="his_proxy.ChandanPharmacyServicesSoap")]
    public interface ChandanPharmacyServicesSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http:www.itdoseinfo.com/2012/11/17/createUpdateItemMaster", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string createUpdateItemMaster(string category, string itemId, string itemName, string mfdName, string genericName, string cimsId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http:www.itdoseinfo.com/2012/11/17/getDcotorIndentByUHID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getDcotorIndentByUHID(string UHID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http:www.itdoseinfo.com/2012/11/17/closeOPDIndent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string closeOPDIndent(string IndentNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http:www.itdoseinfo.com/2012/11/17/getPatientLastAppointmentDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getPatientLastAppointmentDetails(string UHID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http:www.itdoseinfo.com/2012/11/17/getPatientDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getPatientDetails(string UHID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http:www.itdoseinfo.com/2012/11/17/getMedicineAgainstOpdNo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getMedicineAgainstOpdNo(string UHID, string OPDNO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http:www.itdoseinfo.com/2012/11/17/getPatientInfoByIPDNo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getPatientInfoByIPDNo(string IPDNO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http:www.itdoseinfo.com/2012/11/17/getActiveIPDCases", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getActiveIPDCases();
        
        [System.ServiceModel.OperationContractAttribute(Action="http:www.itdoseinfo.com/2012/11/17/doctorMedicineItemSearch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string doctorMedicineItemSearch(string searchType, string prefix);
        
        [System.ServiceModel.OperationContractAttribute(Action="http:www.itdoseinfo.com/2012/11/17/saveIPDIssueReturn", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string saveIPDIssueReturn(string billDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http:www.itdoseinfo.com/2012/11/17/LoadDoctor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string LoadDoctor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http:www.itdoseinfo.com/2012/11/17/getPatientStatusByIndentNo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getPatientStatusByIndentNo(string indentNo, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http:www.itdoseinfo.com/2012/11/17/getPatientStatusByIpdNo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getPatientStatusByIpdNo(string ipdNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http:www.itdoseinfo.com/2012/11/17/closeCompleteIndent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string closeCompleteIndent(string indentNo, string type, string rejectionRemarks);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ChandanPharmacyServicesSoapChannel : eMediShop.his_proxy.ChandanPharmacyServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChandanPharmacyServicesSoapClient : System.ServiceModel.ClientBase<eMediShop.his_proxy.ChandanPharmacyServicesSoap>, eMediShop.his_proxy.ChandanPharmacyServicesSoap {
        
        public ChandanPharmacyServicesSoapClient() {
        }
        
        public ChandanPharmacyServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChandanPharmacyServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChandanPharmacyServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChandanPharmacyServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string createUpdateItemMaster(string category, string itemId, string itemName, string mfdName, string genericName, string cimsId) {
            return base.Channel.createUpdateItemMaster(category, itemId, itemName, mfdName, genericName, cimsId);
        }
        
        public string getDcotorIndentByUHID(string UHID) {
            return base.Channel.getDcotorIndentByUHID(UHID);
        }
        
        public string closeOPDIndent(string IndentNo) {
            return base.Channel.closeOPDIndent(IndentNo);
        }
        
        public string getPatientLastAppointmentDetails(string UHID) {
            return base.Channel.getPatientLastAppointmentDetails(UHID);
        }
        
        public string getPatientDetails(string UHID) {
            return base.Channel.getPatientDetails(UHID);
        }
        
        public string getMedicineAgainstOpdNo(string UHID, string OPDNO) {
            return base.Channel.getMedicineAgainstOpdNo(UHID, OPDNO);
        }
        
        public string getPatientInfoByIPDNo(string IPDNO) {
            return base.Channel.getPatientInfoByIPDNo(IPDNO);
        }
        
        public string getActiveIPDCases() {
            return base.Channel.getActiveIPDCases();
        }
        
        public string doctorMedicineItemSearch(string searchType, string prefix) {
            return base.Channel.doctorMedicineItemSearch(searchType, prefix);
        }
        
        public string saveIPDIssueReturn(string billDetails) {
            return base.Channel.saveIPDIssueReturn(billDetails);
        }
        
        public string LoadDoctor() {
            return base.Channel.LoadDoctor();
        }
        
        public string getPatientStatusByIndentNo(string indentNo, string type) {
            return base.Channel.getPatientStatusByIndentNo(indentNo, type);
        }
        
        public string getPatientStatusByIpdNo(string ipdNo) {
            return base.Channel.getPatientStatusByIpdNo(ipdNo);
        }
        
        public string closeCompleteIndent(string indentNo, string type, string rejectionRemarks) {
            return base.Channel.closeCompleteIndent(indentNo, type, rejectionRemarks);
        }
    }
}
